#!/bin/zsh
#
# This lets you quickly jump into a sandbox directory.
#
# Type:
#
#   s <tab>
#
# ...to autocomplete on all of your projects in the directories specified in
# `functions/_s`. Typically I'm using it like:
#
#    s holm<tab>/bo<tab>
#
# ...to quickly jump into holman/boom, for example.

cd "$SANDBOX_DIR/$1"
