cask_args appdir: '/Applications'

brew 'ack'
brew 'coreutils'
brew 'ffmpeg'
brew 'grc'
brew 'jq'
brew 'libgit2'
brew 'openssl'
brew 'nmap'
brew 'readline'
brew 'tree'
brew 'unrar'
brew 'wget'
brew 'yarn'
brew 'youtube-dl'

cask 'android-studio'
cask 'arduino'
cask 'clamxav'
cask 'daisydisk'
cask 'docker'
cask 'gifox'
cask 'google-chrome'
cask 'graphql-playground'
cask 'jetbrains-toolbox'
cask 'paw'
cask 'sip'
cask 'slack'
cask 'sourcetree'
cask 'the-unarchiver'
cask 'transmit'
cask 'visual-studio-code'
